server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl