server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://rm-uf664qjgc068ae1fzro.mysql.rds.aliyuncs.com:3306/yymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:
    password:
  rabbitmq:
    host:
    port:
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirm-type: correlated
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host:
    # Redis服务器连接端口
    port:
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #  连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 300ms
