# 端口号

# 服务名称

spring:
  datasource:
    url: jdbc:mysql://rm-uf664qjgc068ae1fzro.mysql.rds.aliyuncs.com:3306/yymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root_mysql
    password: Liyuan233
