server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
  rabbitmq:
    host: loaclhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    # 确认消息已发送到交换机（Exchange）选择确认类型为交互
    # publisher-confirms: true
    publisher-confirm-type: correlated

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: yuan13603928090
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #  连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 300ms
#################################################################
#打印SQL
#################################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

